### ISSUE TITLE
Multiple Error Messages when Bookmarking

### ISSUE THREAD

**Issue by valadect** [omar-polo/telescope#13]
**Version**: 0.8.1
**System**: Fedora Asahi Remix 

When I add something to my bookmarks, I either get a `No such file or directory` or occasionally `invalid multibyte character`. This happens on any capsule or gopherhole, however, the link does save to the bookmarks file, and works fine with `:list-bookmarks`

**Comment by omar-polo** [comment]
Thanks for the report!

This was fixed in the main branch (see ba8a119df2b3646ede6415168bd7f56bde6d090a) but that commit is not present in any release yet.

**Comment by omar-polo** [comment]
0.9 is now available and includes this fix :)
