### ISSUE TITLE
pkg-config dependency

### ISSUE THREAD

**Issue by lypanov** [omar-polo/telescope#9]
While not mentioned in the readme pkg-config is used by the libevent detection and as such is also a required dependency. Installing this fixes configure on a minimal debian installation.

**Comment by omar-polo** [comment]
Hello,

I didn't really wanted to depend on pkg-config because it makes the life harder on some setups, but I had some troubles with libevent detection and so I started depending on it.  I'll need to revise that sometimes, but for the time being I've added the note on the README, thanks! :)

**Comment by omar-polo** [comment]
Took a while :)

since 0.9 we don't use libevent and pkg-config was not used by the configure script.  Now I've also removed the last mentions of it.
